
name: mineunit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mt-mods/mineunit-actions@badger
      with:
        badge-secret: ${{ secrets.MineunitBadgesAPIKey }}
