name: mineunit

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: mineunit
      uses: mt-mods/mineunit-actions@master
    - uses: RubbaBoy/BYOB@v1.3.0
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        NAME: "${{ steps.mineunit.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: KeisukeYamashita/create-comment@v1
      if: failure() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      with:
        check-only-first-line: true
        comment: |
          ## Some tests failed, test log follows:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
